[project]
name = "speech-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "language-tool-python>=3.2.2",
    "openai>=2.15.0",
    "openai-whisper>=20250625",
    "pandas>=2.3.3",
]
